/**
 * Local migration helper built on Prisma's WASM schema engine.
 *
 * Why: `prisma migrate dev` downloads a native schema engine binary on first run.
 * In restricted networks (CI sandboxes, air-gapped servers) that download fails.
 * This script talks to the same engine compiled to WebAssembly (bundled in
 * node_modules), so it works fully offline.
 *
 * Usage:
 *   tsx scripts/migrate.ts                 # apply pending migrations (like `migrate deploy`)
 *   tsx scripts/migrate.ts --create init   # create a new migration from schema diff
 *   tsx scripts/migrate.ts --reset         # drop everything and re-apply all migrations
 *
 * In normal environments prefer the official commands:
 *   npx prisma migrate dev / npx prisma migrate deploy
 */
import 'dotenv/config';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { PrismaPg } from '@prisma/adapter-pg';
import { bindMigrationAwareSqlAdapterFactory } from '@prisma/driver-adapter-utils';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, '..');
const schemaPath = path.join(root, 'prisma', 'schema.prisma');
const migrationsDir = path.join(root, 'prisma', 'migrations');

const args = process.argv.slice(2);
const flag = (name: string) => args.includes(name);
const opt = (name: string) => {
  const i = args.indexOf(name);
  return i >= 0 ? args[i + 1] : undefined;
};

const url = process.env.DATABASE_URL;
if (!url) {
  console.error('DATABASE_URL is not set');
  process.exit(1);
}

function loadMigrationList() {
  fs.mkdirSync(migrationsDir, { recursive: true });
  const lockPath = path.join(migrationsDir, 'migration_lock.toml');
  const dirs = fs
    .readdirSync(migrationsDir, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => d.name)
    .sort();
  return {
    baseDir: migrationsDir,
    lockfile: {
      path: 'migration_lock.toml',
      content: fs.existsSync(lockPath) ? fs.readFileSync(lockPath, 'utf8') : null,
    },
    shadowDbInitScript: '',
    migrationDirectories: dirs.map((name) => {
      const file = path.join(migrationsDir, name, 'migration.sql');
      return {
        path: name,
        migrationFile: {
          path: 'migration.sql',
          content: fs.existsSync(file)
            ? { tag: 'ok' as const, value: fs.readFileSync(file, 'utf8') }
            : { tag: 'error' as const, value: 'migration.sql not found' },
        },
      };
    }),
  };
}

async function main() {
  const wasm = await import('@prisma/schema-engine-wasm');
  const schema = fs.readFileSync(schemaPath, 'utf8');
  const factory = bindMigrationAwareSqlAdapterFactory(new PrismaPg({ connectionString: url }));
  const engine = await wasm.SchemaEngine.new(
    { datamodels: [['prisma/schema.prisma', schema]] },
    () => undefined,
    factory,
  );
  const filters = { externalTables: [], externalEnums: [] };

  if (flag('--reset')) {
    console.log('⚠  Resetting database…');
    await engine.reset({ filter: filters });
  }

  // Always bring the database up to date first.
  const applyAll = async () => {
    const applied = await engine.applyMigrations({ migrationsList: loadMigrationList(), filters });
    for (const m of applied.appliedMigrationNames) console.log(`✔ Applied ${m}`);
    return applied.appliedMigrationNames.length;
  };

  if (flag('--create')) {
    const name = (opt('--create') ?? 'migration').replace(/[^a-zA-Z0-9_]+/g, '_');
    const existing = loadMigrationList();
    // First migration: diff from an empty database → desired schema (no shadow DB needed).
    // Later migrations: diff from the applied migration history (uses a temporary shadow DB).
    const from =
      existing.migrationDirectories.length === 0
        ? ({ tag: 'empty' } as const)
        : ({ tag: 'migrations', ...existing } as const);
    const diff = await engine.diff({
      from,
      to: { tag: 'schemaDatamodel', files: [{ path: 'prisma/schema.prisma', content: schema }] },
      script: true,
      exitCode: null,
      filters,
    });
    const script = (diff.stdout ?? '').trim();
    if (!script || script === '-- This is an empty migration.') {
      console.log('✔ Schema is already in sync — no migration created.');
    } else {
      const stamp = new Date().toISOString().replace(/[-:TZ.]/g, '').slice(0, 14);
      const dirName = `${stamp}_${name}`;
      const dir = path.join(migrationsDir, dirName);
      fs.mkdirSync(dir, { recursive: true });
      fs.writeFileSync(path.join(dir, 'migration.sql'), script + '\n');
      const lockPath = path.join(migrationsDir, 'migration_lock.toml');
      if (!fs.existsSync(lockPath)) {
        fs.writeFileSync(
          lockPath,
          '# Please do not edit this file manually\n# It should be added in your version-control system (e.g., Git)\nprovider = "postgresql"\n',
        );
      }
      console.log(`✔ Created migration ${dirName}`);
    }
  }

  const count = await applyAll();
  if (count === 0) console.log('✔ Database is up to date.');
  process.exit(0);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
